### ISSUE TITLE
Request for APK Release

### ISSUE THREAD

**Issue by yance-dev** [wuhongsheng/S2SAndroidClient#2]
I'm interested in trying out this app but notice there's no APK available in the releases. Would it be possible to provide a pre-built APK, or alternatively, add build instructions to the README?

Looking forward to testing the app. Thanks for considering!

**Comment by wuhongsheng** [comment]
> I'm interested in trying out this app but notice there's no APK available in the releases. Would it be possible to provide a pre-built APK, or alternatively, add build instructions to the README?
> 
> Looking forward to testing the app. Thanks for considering!

https://github.com/wuhongsheng/S2SAndroidClient/releases/tag/v1.0.0
